#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Booking
#        - App\Entity\Chef
#        - App\Entity\Commentaire
#        - App\Entity\User

easy_admin:
    entities:
        User:
            class: App\Entity\User
            list:
              fields:
                  - id
                  - prenom
                  - nom
                  - password
                  - email
                  - { property: 'roles', label: 'Rôles', type: json_array}
            form:
              fields:
                  - email
                  - password
                  - nom
                  - prenom
                  - { property: 'roles', label: 'Rôles', type: choice, type_options: {expanded: true, multiple: true, choices: {'Utilisateur':'ROLE_USER', 'Administrateur':'ROLE_ADMIN'}}}
        Booking:
            class: App\Entity\Booking
        Chef:
            class: App\Entity\Chef
            list:
                fields:
                  - id
                  - nom
                  - prenom
                  - { property: 'image', type: 'image', base_path: '%app.path.chef_images%' }
                  - presentation
                  - type_de_cuisine
                  - menu
            form:
                fields:
                  - nom
                  - prenom
                  - { property: 'imageFile', type: 'vich_image' }
                  - presentation
                  - type_de_cuisine
                  - menu
        Menu:
            class: App\Entity\Menu
        Commentaire:
            class: App\Entity\Commentaire
