easy_admin:
    site_name: 'DomiLicious -  <b>Espace Admin</b>'
    
    user:
        display_name: true
        display_avatar: false
    entities:
        User:
            class: App\Entity\User
            label: 'Utilisateurs'
            list:
              title: "Liste des utilisateurs"  
              fields:
                  - id
                  - prenom
                  - nom
                  - adresse
                  - telephone
                  - password
                  - email
                  - { property: 'roles', label: 'Rôles', type: json_array}
            form:
              fields:
                  - email
                  - password
                  - nom
                  - prenom
                  - adresse
                  - telephone
                  - { property: 'roles', label: 'Rôles', type: choice, type_options: {expanded: true, multiple: true, choices: {'Utilisateur':'ROLE_USER', 'Administrateur':'ROLE_ADMIN'}}}
        Booking:
            class: App\Entity\Booking
            label: 'Reservations'
            list:
              title: "Liste des reservations"
              fields:
                  - dateReservation
                  - message
            form:
              fields:
                  - dateReservation
                  - message
        Chef:
            class: App\Entity\Chef
            label: 'Chefs'
            list:
              title: "Liste des chefs"
              fields:
                  - nom
                  - prenom
                  - { property: 'image', type: 'image', base_path: '%app.path.chef_images%' }
                  - presentation
            form:
              fields:
                  - nom
                  - prenom
                  - { property: 'imageFile', type: 'vich_image', base_path: '%app.path.chef_images%' }
                  - presentation
        Menu:
            class: App\Entity\Menu
            label: 'Menus'
            list:
              title: "Liste des menus proposés"
              fields:
                  - entree
                  - plat
                  - dessert
                  - { property: 'image', type: 'image', 'base_path': '/images' }
            form:
              fields:
                  - entree
                  - plat
                  - dessert
                  - image
